name: Deploy to Amazon ECR

trigger:
  branches:
    include:
      - main  # Cambiar por la rama principal de tu repositorio

jobs:
- job: build_and_push_image
  displayName: 'Build and Push Docker Image to ECR'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self

  - script: |
      # Instalar dependencias, si es necesario
      # npm install, por ejemplo
      docker build -t my-ecr-repo:latest .
      docker login -u AWS -p $(AWS_ACCESS_KEY_ID) -e none $(AWS_ECR_REGISTRY)
      docker tag my-ecr-repo:latest $(AWS_ECR_REGISTRY)/my-ecr-repo:latest
      docker push $(AWS_ECR_REGISTRY)/my-ecr-repo:latest
    displayName: 'Build, Tag, and Push Docker Image'
    env:
      AWS_ACCESS_KEY_ID: ${{ AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ AWS_SECRET_ACCESS_KEY }}
      AWS_ECR_REGISTRY: '<your-aws-account-id>.dkr.ecr.<your-aws-region>.amazonaws.com'

